# Spring config
spring:
  application:
    name: gas-out-api-dev
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher